### ISSUE TITLE
lz10 decompression error.

### ISSUE THREAD

**Issue by MichaelHinrichs** [v69ar73aqvc/dsdecmp#1]
This file from Yoshi's Island DS returns the "Cannot go back more than already written." error.

https://drive.google.com/file/d/19TPEzwOrj_antAUvW6yPUbn5PeHvR7EO/view?usp=sharing

**Comment by v69ar73aqvc** [comment]
Software does not use common LZ10. This is outside the scope of the library.
https://www.smwcentral.net/?p=viewthread&t=54178&page=1&pid=884740#p884740
Note that this repository is a fork of code written by barubary.
https://github.com/Barubary/dsdecmp

**Comment by MichaelHinrichs** [comment]
Barubary hasn't updated that dsdecmp in a decade. There are no responses from them on any issues. I tried asking for help in Kuriimu 2, which gives the same error, but got no response yet. It doesn't seem like there is a single program with a LZ10 decompression function that can decompress this file correctly.
